remote_theme: tomjoht/documentation-theme-jekyll@gh-pages

topnav_title: PADrend Tutorials
site_title: PADrend Tutorials
company_name: Benjamin Eikel, Claudius Jähn, Ralf Petring, Sascha Brandt
repository: PADrend/Tutorials

exclude:
- .gitignore
- Tools/
- tmp
- build_site.sh
- build_test.sh

feedback_disable: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "API"
    values:
      layout: "api"
      comments: false
      search: true
      sidebar: api_sidebar
      topnav: topnav
      
sidebars:
- home_sidebar
- api_sidebar
- e_api_sidebar
